/*
Meteor.subscribe('currencies');
Meteor.subscribe('customerInfo');
Meteor.subscribe('images');
Meteor.subscribe('transactions');
Meteor.subscribe('withdrawRequest');
Meteor.subscribe('voucher');
Meteor.subscribe('accountStatus');
*/